Feat: Broker Auth + Additional Targets
ManoManoTech/pact-graph-network pull request #17
Opened 2023-05-22 11:42 UTC by YOU54F

Hey @guiyomh 

Thanks for releasing this tool, I remember when you told us about it back in December, I came back to my mind and thought it would be good to get auth based support in place, it looks like you had most of the work done, just needed exposing in user flags.

I also added a load more targets as well, because rustup/cross is awesome :)

Happy to split out the changes.

There are a couple of things that will need removing prior to merging, I set the value manually in the workflow file, as it wasn't picking up the next version, and updated a load of the action tags as they were deprecated.

2023-06-05 07:16 UTC, guiyomh commented
@YOU54F thank for your contribution.I'll review it today. Sorry for the tartive review.

2023-06-05 07:36 UTC, guiyomh approved these changes

2023-06-05 07:49 UTC, guiyomh requested changes
The changelog is generated by the pipeline, so you need to remove it from your PR to avoid conflicts.

Similarly, version bumping is done automatically by the pipeline. You can't predict what the version number will be, it depends on the merge order of the PRs. So leave it to the pipeline.

Otherwise, thanks for the contribution, it's great 🤩 .

2023-06-05 11:12 UTC, YOU54F commented
No rush at all @guiyomh , thanks for taking a look 👍🏾 

Changes addressed now and merged main in.

thanks buddy

2023-06-08 13:09 UTC, guiyomh approved these changes

2023-06-08 13:09 UTC, guiyomh commented on CHANGELOG.md
> +
Automatically generated by the CI. Please remote it from your PR.

2023-06-08 13:09 UTC, guiyomh commented on Cargo.toml
> +version = "0.8.0"
Bumping the  version is done by the pipeline.  Please remove it from your PR.

2023-06-08 13:18 UTC, merged

2023-06-08 13:52 UTC, guiyomh commented
It's merged! thank for your contrib.